plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.protector'
    compileSdk 34
    ndkVersion '26.1.10909125'

    defaultConfig {
        applicationId 'com.example.protector'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17 -O2 -fvisibility=hidden'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'com.google.android.material:material:1.11.0'
}
